# Specifies the base image.
FROM nginx:latest

# remove default config
RUN rm /etc/nginx/conf.d/default.conf

COPY ./docker/nginx/conf/app.conf /etc/nginx/conf.d/app.conf
COPY ./docker/nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/conf/ssl/dev.blick.ch.crt /etc/ssl/certs/dev.blick.ch.crt
COPY ./docker/nginx/conf/ssl/dev.blick.ch.key /etc/ssl/certs/dev.blick.ch.key
